//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLYARDIM
    {
        public int YardimID { get; set; }
        public string Soru { get; set; }
        public string Cevap { get; set; }
    }
}
